language: php

php:
  - 5.5
  - 5.6
  - 7

services:
  - mysql

before_script:
  - mkdir deploytest
  - cd deploytest
  - composer self-update
  - composer create-project instante/skeleton . dev-develop --no-interaction --stability="dev" --prefer-source
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - mysql -e 'create database instante_test;'

script: ./tests/skeleton-test.sh
